// Code generated by Slice Machine. DO NOT EDIT.

import Hero from './Hero';
import Image from './Image';
import InfoTextBlock from './InfoTextBlock';
import ProjectText from './ProjectText';
import TextWithFeatures from './TextWithFeatures';
import TextWithImage from './TextWithImage';

export {
	Hero,
	Image,
	InfoTextBlock,
	ProjectText,
	TextWithFeatures,
	TextWithImage,
};

export const components = {
	hero: Hero,
	image: Image,
	info_text_block: InfoTextBlock,
	project_text: ProjectText,
	text_with_features: TextWithFeatures,
	text_with_image: TextWithImage,
};
